### PR TITLE
Update TFC UI Images

### PR DESCRIPTION
**Pull request by jboero**
New style of UI.
https://hashicorp.slack.com/archives/CA8TSAV1T/p1668677780589349

### CODE REVIEW

**Comment by lucymhdavies** [comment]
Do we want to do this with a TFC Org that isn't part of the Projects internal beta, to show what it looks like right now?

(In case the projects UI changes in future)

**Comment by jboero** [comment]
@lucymhdavies I thought the new UI was out of beta?  Mebbe not?

**Comment by lucymhdavies** [comment]
New UI, yes. Projects, no.

**Comment by jboero** [comment]
Closing to stop the Slack reminder.

**Pull request closed without merging**
