### PR TITLE
Make RBAC group name test less strict

### PR DESCRIPTION
**Pull request by scarolan**
See #278  by @dlectronique

### CODE REVIEW

**Review by dlectronique — APPROVED** [review]
Yay, looks good to me :)

**Review by rberlind — COMMENTED** [review]
Wouldn't the same change be needed in the TFC for Azure and GCP tracks?

**Comment by dlectronique** [comment]
I have not checked the other tracks, but I'm assuming this would work for most of them

**Comment by scarolan** [comment]
Roger is correct. I will add the fix to the other tracks.

**Comment by scarolan** [comment]
@rberlind   let's wait until end of day to merge this

**Review by rberlind — APPROVED** [review]
Thanks for adding Azure and GCP fixes. @scarolan

**Pull request merged**
