### PR TITLE
IL-632 Fixing issues related to TFCB Licensing changes

### PR DESCRIPTION
**Pull request by thomashashi**

### CODE REVIEW

**Comment by thomashashi** [comment]
Draft for now

**Comment by omkensey** [comment]
@thomashashi when you're back from PTO, what's the best way to move this PR through to completion?  I know you had test versions of these tracks built with these changes but I'm not sure of the current status.

**Comment by thomashashi** [comment]
> @thomashashi when you're back from PTO, what's the best way to move this PR through to completion? I know you had test versions of these tracks built with these changes but I'm not sure of the current status.

Right now we need three things:
1. @hashi-randy and @seanwalker5 need to sign the HashiCorp CLA to keep Legal happy
2. We need to work on the conflicts noted above
3. Test and I need someone to review

**Comment by thomashashi** [comment]
> Where would I find the CLA to sign?

Go up to https://github.com/hashicorp/field-workshops-terraform/pull/369#issuecomment-1558028130 and click on the "Read and Sign" link. I believe that should do it.

**Pull request closed without merging**
